### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#1]
hey i have error on day0.cpp and day1.cpp please take a min and help me to solve the code

please read contributing.md for more details.

**Comment by abraham-john-paul** [comment]
Hi , can i help with this?

**Comment by rahulsain3000** [comment]
i need help in this: https://github.com/rahulsain3000/Hackerrank_30daysOFcode/issues/2

Also, you could help me in this repo: https://github.com/rahulsain3000/hello-world/issues/2

**Comment by shivangdubey** [comment]
I would like to this error.
