### ISSUE TITLE
updation of links in readme

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#117]
any improvement for readme file is most welcome here

**Comment by Code-Recursion** [comment]
I would love to improve the readability of the README file :) , can i go ahead?

**Comment by dalalvarun** [comment]
I would like to add some badges and also make some format and grammatical corrections in readme.md

**Comment by rahulsain3000** [comment]
ok @dalalvarun go ahead

**Comment by amishaagarwal1998** [comment]
I would like to help too!

**Comment by amishaagarwal1998** [comment]
Thank you! Will update asap

**Comment by amishaagarwal1998** [comment]
Added C# column in Read me along with ticks on completed codes. Please review.

**Comment by rahulsain3000** [comment]
@amishaagarwal1998 If you're countering issue in resolving your PR you can ask here.
We are ready to help each other

**Comment by amishaagarwal1998** [comment]
Yes actually in the read me file there was an issue of readability.
![image](https://user-images.githubusercontent.com/34367385/94930571-4022a900-04e4-11eb-9a88-650831e63c5e.png)
I was making it visually better for the contricutor
![image](https://user-images.githubusercontent.com/34367385/94930680-65171c00-04e4-11eb-93f7-35c302c44f93.png)
This is the merge conflict as per me. Am I wrong here? Please let me know.

**Comment by rahulsain3000** [comment]
The conflict occurred because I recently made a change in readme file and that is not updated in your local repo.
Copy readme file from this repo and make changes accordingly in your repo then send a PR

**Comment by amishaagarwal1998** [comment]
Okay

**Comment by dalalvarun** [comment]
> ok @dalalvarun go ahead and please add another column for C# language and cross check the file that is in the repo .
> Mark it as complete

Ok sure
