### ISSUE TITLE
complete this series in Javascript

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#196]
please complete remaining code in JS

**Comment by codeR49** [comment]
i want to contribute

**Comment by rahulsain3000** [comment]
check readme file you will get an idea

**Comment by rahulsain3000** [comment]
> i want to contribute, which one to complete

please complete day21 and day27

**Comment by adrikagupta** [comment]
Hey. I am interested in doing questions 21 and 27. Can you assign it to me?

**Comment by Reetpriye** [comment]
Hi. I'm interested in contributing. I'm well familiar with JavaScript kindly assign me some task.

**Comment by rahulsain3000** [comment]
@Reetpriye Hi, you can make cleaner code for existing solution and can make code readable by adding comment.

If you want to add code for day21 and day27 please note the PR will be merged on First come first served basis.
Kindly note, also update readme file and mark a TICK across that day in JS.

**Comment by GauravPoosarla** [comment]
I would like to work on day-2, as it hasn't been done yet in JavaScript, please assign it to me.

**Comment by GauravPoosarla** [comment]
I have sent a PR.

**Comment by Reetpriye** [comment]
> @Reetpriye Hi, you can make cleaner code for existing solution and can make code readable by adding comment.
> 
> If you want to add code for day21 and day27 please note the PR will be merged on First come first served basis.
> Kindly note, also update readme file and mark a TICK across that day in JS.

I've added comments to Day2 problem in C++ and made some modifications as there was unnecessary typecasting. Kindly merge my PR.
