### ISSUE TITLE
complete this series in Go

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#198]
please complete remaining code in Go

**Comment by susanka068** [comment]
I'd like to work on this ! please assign me this issue @rahulsain3000

**Comment by titinlib** [comment]
I also want to work on this, can you please assign me too?

**Comment by GajjarMiten** [comment]
Hey @rahulsain3000!
Can I work on it?

**Comment by GauravPoosarla** [comment]
Please assign me i want to work on it, will complete it.

**Comment by Abhishek4uh** [comment]
Hey @rahulsain3000  Plz assign this to me, I'm really want to work on this.

**Comment by rahulsain3000** [comment]
@Abhishek4uh Please cooperate with @GauravPoosarla as he is already uploading code regarding this issue.
You can discuss here

**Comment by preethamrn** [comment]
Hi Rahul, I'd like to work on this as well if possible.

**Comment by dev117uday** [comment]
@rahulsain3000  i have experience working in Golang, please assign me if possible
