### ISSUE TITLE
complete the 30-days code solution

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#2]
anyone interested can help by completing solution of this series or providing 30day code solution in any other language(Java, C, Python is preferred)

**Comment by beingaryan** [comment]
I am interested in doing so. Is the issue resolved for day0.cpp and day1.cpp? Can you assign this task to me?

**Comment by alvinma** [comment]
Hi! I can help with the C, C++, and Python implementation. Is there a way to see the problem from HackerRank early, or do I need to wait each day for the day's problem to be unlocked?

**Comment by BhaskarJoshi-01** [comment]
Hey! Can I help ??

**Comment by rahulsain3000** [comment]
please try to complete this series in c++ or with any other language(java/python) once completed i will merge the pr

**Comment by Exter-dg** [comment]
I would like to work on this (C++). Can you assign this to me too?

**Comment by maayeesha** [comment]
I would like to contribute to the repo!

**Comment by rahulsain3000** [comment]
Please note that , It will count as a valid PR if you make a PR in October not now

It must have a valid code in the language that is not yet in this repo.

Hope I clear all your doubts.

**Comment by rasacharjee** [comment]
I also want to work on this(c++) , can you please assign this to me also

**Comment by Pulkitmahajan01** [comment]
I would also like to work on the same in c++. Could you please assign this to me.

**Comment by h4rz** [comment]
Hey @rahulsain3000, I would love to work on Python3 solutions. Please assign. Thanks!

**Comment by h4rz** [comment]
One suggestion - It would be better to create a language-specific issue and assign other contributors who are interested in it so, that each dev can know who else is working and they can collab together if they want to.

**Comment by aleena-james** [comment]
I would like to contribute to this repo in C++. Could you please assign this to me.

**Comment by muskanapp** [comment]
Hey @rahulsain3000, I would love to contribute to this repo. I would love to work on Python3 and C++ solutions. Please assign. Thanks!

**Comment by rahulsain3000** [comment]
@muskanapp you can do python 3 solutions, c++ solutions has been already assigned.

**Comment by h4rz** [comment]
> Hey @rahulsain3000, I would love to work on Python3 solutions. Please assign. Thanks!

> @muskanapp you can do python 3 solutions, c++ solutions has been already assigned.

@rahulsain3000, I'm already working on python3 and I'm already assigned.

**Comment by rahulsain3000** [comment]
ok @h4rz I didn't see sorry @muskanapp  try in another language that has been not assigned yet.

**Comment by muskanapp** [comment]
@h4rz are you gonna contribute to all the Python 3 solutions? I saw multiple people assigned to the same language, that's why I asked.

**Comment by h4rz** [comment]
@muskanapp, Hackerrank's `30 days of code` makes only one problem available to solve per day and I'm already on day 3. So if we join then it will create a merge conflict or there will be duplicate solutions in the repo.

**Comment by muskanapp** [comment]
@rahulsain3000 Can I contribute to the repo in C Or Java?

**Comment by rahulsain3000** [comment]
Please note that to reduce the clashes regarding same people working on same language. I am creating language specific issue as suggested by @h4rz and closing this one.

I will assign one person to work on 1 language and it will be on basis of First Come First Serve.

**Comment by shikharmaxx** [comment]
Hello @rahulsain3000, I would like to contribute in JavaScript. Could you please assign me that ?

**Comment by rahulsain3000** [comment]
ok @shikharmaxx  I am creating a issue for JS I will assign you there
