### ISSUE TITLE
Testing for Javascript Solutions

### ISSUE THREAD

**Issue by sunnysetia93** [rahulsain3000/Hackerrank_30daysOFcode#201]
Hi 
I would like to add test cases for existing JS solutions.

_1. Will be adding a test folder in the 30daysOFcode_JavaScript.
2. Separate test case file for each solution._

Please assign this issue to me. I'll pick this up.

Thanks

**Comment by rahulsain3000** [comment]
@sunnysetia93, can you explain how test cases will help the people? Is it already there in their site

**Comment by sunnysetia93** [comment]
Though test cases are there on hacker-rank, they are not visible.but adding a custom test cases will promote overall software development.
Also, since 30 days of code promotes learning a new language by solving different problems, having test cases will also teach the user how to create a test case and test the solution thoroughly which hacker-rank doesn't provide

**Comment by sunnysetia93** [comment]
Though test cases are there on hacker-rank, they are not visible. but adding a custom test cases will promote overall software development (from development to testing).
Also, since 30 days of code promotes learning a new language by solving different problems, having test cases will also teach the user how to create a test case and test the solution thoroughly which hacker-rank doesn't give visibility off.

**Comment by sunnysetia93** [comment]
In the readme, a column named testing can be added to provide visibility.

**Comment by rahulsain3000** [comment]
@sunnysetia93 , I think there is no need to update readme regarding test cases. 
Regarding your test case idea, go ahead and make sure that you send only 1 PR that has all 30 day test case in it.

**Comment by sunnysetia93** [comment]
Each test file will contain 2 to 3 test cases and there are 30 files. 
It will take some time, So for now, I'll create a PR for the first 5 problems.

You can review it, accept the PR and there on I can continue with the rest.
Works?

**Comment by rahulsain3000** [comment]
@sunnysetia93 I am assuming that you're participating in Hacktoberfest and you need 4 valid PR's.
So, complete 30 files in 4-5 PR if that's fine.

**Comment by sunnysetia93** [comment]
Sure. I'll complete all the 30.

**Comment by gandalf0151** [comment]
This is a good one
Are you writing tests or just the test cases @sunnysetia93

**Comment by sunnysetia93** [comment]
Thanks, @gandalf0151 
I'll be writing test cases using a Jest.

**Comment by gandalf0151** [comment]
oh nice
I don't know Jest
Heard about it earlier
Your code will definitely help me in getting started as finding tests for these kind of small programs won't be easy
Thanks

**Comment by gandalf0151** [comment]
@rahulsain3000 Please merge those PRs as those will be a valuable addition to your profile too

**Comment by rahulsain3000** [comment]
@gandalf0151 I am ready to merge his contribution in this repo.

**Comment by gandalf0151** [comment]
👍👍

**Comment by sunnysetia93** [comment]
Raised a PR: #228 
If this PR is fine, will keep raising PR for other solutions as well.

@gandalf0151 - once this PR is merged, you can refer to my solutions and contribute as well :)

**Comment by gandalf0151** [comment]
Yeah, sure thing
Will definitely look into it 😀

**Comment by coder-023** [comment]
Can you please suggest me tasks?
Sorry for such a lame question, I am just a beginner

**Comment by rahulsain3000** [comment]
@coder-023 Hey, we welcome beginners to our Repo, you can update  Readme.md file and add a column for PHP language and mark tick across the code that are there in the folder

**Comment by coder-023** [comment]
Ok,I will do it. Please assign me this task

**Comment by sunnysetia93** [comment]
@rahulsain3000 
can you add Hacktoberfest etc labels to this issue, so that people can join in and contribute?

**Comment by rahulsain3000** [comment]
@sunnysetia93 When  you are done please close this issue

**Comment by BRZ-OS** [comment]
Hi @rahulsain3000 I'm a beginner looking for some task to contribute (and practice PR too)
is there some task remain for the beginner yet?

**Comment by rahulsain3000** [comment]
@BRZ-OS Head over to my other hello world repo or if you know java then to java_dsa repo

**Comment by sunnysetia93** [comment]
> @sunnysetia93 When you are done please close this issue

Sure @rahulsain3000

**Comment by BRZ-OS** [comment]
Hi @rahulsain3000 just update something for your hello world repo, thanks for your task 👍
