### ISSUE TITLE
complete this series in c++

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#22]
if you want to collaborate with other you can discuss there.

please note make a folder and name it "Hackerrank_30daysOFcode_in_C++"

note that I have already assigned this issue to some people in #2 so they are preferred first as they are already working on this issue

**Comment by hnishal** [comment]
can I get to work on this issue?

**Comment by rahulsain3000** [comment]
@hnishal hey can you wait for 24 hours as I waiting for the PR from assigned person that is mentioned in #2 

If no one send a PR in C++ then I will assign you

**Comment by hnishal** [comment]
@rahulsain3000 any other issue i can work upon till then?

**Comment by rahulsain3000** [comment]
You could improve readme file as a part of documentation. Just send a PR.

**Comment by aleena-james** [comment]
I will work on this..

**Comment by shibrahmachari** [comment]
hi, is there anything i can contribute too?

**Comment by rahulsain3000** [comment]
> You could improve readme file as a part of documentation. Just send a PR.

@shibrahmachari

**Comment by rahulsain3000** [comment]
@aleena-james I have assigned you this issue please try to complete this series(no time bound)

**Comment by hnishal** [comment]
@rahulsain3000 what changes or addition you want in the readme.md?

**Comment by shibrahmachari** [comment]
@rahulsain3000  could you please assign me then and apart from documentation can I help with something else?

**Comment by rahulsain3000** [comment]
@hnishal any further improvement you want to add

**Comment by sherwin2000** [comment]
please give me this issue

**Comment by raj1238** [comment]
I have added solutions to the last three days and opened up PRs. please do let me know if I can help in any other way as well.

**Comment by rahulsain3000** [comment]
Only day18.cpp is required to complete this series. @aleena-james are you gonna do it?

**Comment by sawwwrabhp** [comment]
Hey, I'm interested. Can i work on it? Or any other cpp solution?

**Comment by amishaagarwal1998** [comment]
Hi I am interested. Can I work on it?

**Comment by rahulsain3000** [comment]
please add day18 solution in C++ folder and then I will close this issue.

Just make a PR

**Comment by 23krishna** [comment]
> if you want to collaborate with other you can discuss there.
> 
> please note make a folder and name it "Hackerrank_30daysOFcode_in_C++"
> 
> note that I have already assigned this issue to some people in #2 so they are preferred first as they are already working on this issue

Hello Can I get to work on this issue?

**Comment by rahulsain3000** [comment]
> please add day18 solution in C++ folder and then I will close this issue.
> 
> Just make a PR

@23krishna

**Comment by sawwwrabhp** [comment]
> 
> 
> > please add day18 solution in C++ folder and then I will close this issue.
> > Just make a PR
> 
> @23krishna

hey, i did that. made a pr

**Comment by rahulsain3000** [comment]
@everyone this series is completed but check other issues
