### ISSUE TITLE
complete this series in Php

### ISSUE THREAD

**Issue by pkpawankushwaha** [rahulsain3000/Hackerrank_30daysOFcode#227]
day0 to day6 solutions are added...complete other code in Php

**Comment by rahulsain3000** [comment]
@pkpawankushwaha  Are you gonna complete it?

**Comment by raj1238** [comment]
I have submitted the solutions to Day 6 and Day7. Please review it @rahulsain3000

**Comment by rahulsain3000** [comment]
@raj1238 Successfully merged

**Comment by raj0710** [comment]
@rahulsain3000 Can I contribute to this issue ?

**Comment by rahulsain3000** [comment]
@everyone Is someone still working on PHP? The questions that are left can't be done on PHP?

**Comment by aastha0507** [comment]
Can I take this issue? I can write all the remaining codes in php.

**Comment by rahulsain3000** [comment]
Sure @aastha0507
