### ISSUE TITLE
complete this series in c

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#23]
if you want to collaborate with other you can discuss there.

please note make a folder and name it "Hackerrank_30daysOFcode_in_C"

note that I have already assigned this issue to some people in #2 so they are preferred first as they are already working on this issue

**Comment by Harshal0506** [comment]
I would love to work on it it will be a great learning experience for me 

I will try my best to make it beginner friendly and sweet  👍🏻 

Cheers!! 
Thanks for this wonderful appourtunity in advance
jai shree krishna

**Comment by rahulsain3000** [comment]
Please try to complete this series (no time bound)

**Comment by siddharthrajaraja** [comment]
@Harshal0506  May I assist you?

**Comment by amishaagarwal1998** [comment]
I am also willing to help

**Comment by rahulsain3000** [comment]
Please @siddharthrajaraja @amishaagarwal1998 collaborate with @Harshal0506

**Comment by Jainchhavi16** [comment]
Hi, you have mentioned the language as C but they are contributing in C++. Will there be a separate folder for solutions in C too?
If so, can I work on it?

**Comment by Bharathwaj3003** [comment]
i also want to work in C. I see that they all are doing in C++ so myself and @Jainchhavi16 will work in C?

**Comment by Bharathwaj3003** [comment]
hi @rahulsain3000 can myself and @Jainchhavi16 work for the C part of this repository?

**Comment by rahulsain3000** [comment]
@Jainchhavi16 there is already a c folder in the code and has day0 solution in it as .md file

@Bharathwaj3003 

> Please @siddharthrajaraja @amishaagarwal1998 collaborate with @Harshal0506

**Comment by GauravPoosarla** [comment]
Please assign me for C.

**Comment by rahulsain3000** [comment]
@GauravPoosarla please discuss here with other developers

**Comment by jainaayush01** [comment]
Hey please let me know if i can help on some issues.

**Comment by jainaayush01** [comment]
I am not able to see what task has already been assigned. So please guide me.

**Comment by rahulsain3000** [comment]
> @GauravPoosarla please discuss here with other developers

@jainaayush01 ask others on what day they are working on and ask for a day solution that you could help them with

**Comment by GauravPoosarla** [comment]
Can you just tell me on what days i can work on?

**Comment by jainaayush01** [comment]
Thanks for helping me out @rahulsain3000 .
Hey @Harshal0506 Can i help you with solutions for Day 20 and 22.

**Comment by Harshal0506** [comment]
hey @jainaayush01  here is my code  for [Day 20](http://pastie.org/p/50Ezr2BbSnhjVMPP61NPu6) 
i need to add comments and some resources 
### have a look

**Comment by amishaagarwal1998** [comment]
Hey @Harshal0506  I have created a PR for ques 3 and 7. Please review :-)

**Comment by GauravPoosarla** [comment]
I am doing from day 10 to day 14.

**Comment by gandalf0151** [comment]
Sent PR #114 for Day 20

**Comment by jainaayush01** [comment]
Hey @Harshal0506 ,
I have completed the Day 20 22 and 24. I will add the comments in the respective files.
Is it ok.

**Comment by jainaayush01** [comment]
since for day 20 PR has been merged i am making PR for the 22 and 24.
Thanks

**Comment by Himith** [comment]
Please assign some questions to  me too .

**Comment by amishaagarwal1998** [comment]
I'll add ques 6,10.

**Comment by Code-Recursion** [comment]
I would be glad to complete the full 30daysofcode of hackerrank.

**Comment by gandalf0151** [comment]
Day 26 PR #148

**Comment by gandalf0151** [comment]
Day 27 can't be done in C

**Comment by rahulsain3000** [comment]
ok @gandalf0151

**Comment by Anmol55555** [comment]
Please assign me this task.

**Comment by Harshal0506** [comment]
what is assigned to @Anmol55555 ?

**Comment by gandalf0151** [comment]
All of the programs which are left in 30 days of code, can't be implemented
in C
So, it's better to put a cross mark on those

**Comment by Anmol55555** [comment]
Can all this code can be written in c++?

**Comment by gandalf0151** [comment]
Separate folder is available for C++
already completed

**Comment by Anmol55555** [comment]
ok

**Comment by rahulsain3000** [comment]
Thanks @gandalf0151 for the info. So may I close this issue?

**Comment by gandalf0151** [comment]
yes all of the C code is completed
thanks for this opportunity to collaborate 😊

**Comment by rahulsain3000** [comment]
Thanks @everyone for contributing in this repo.

**Comment by Harshal0506** [comment]
Thanks  @rahulsain3000 Bhaiya for such a great opportunity 👍🏻
