### ISSUE TITLE
complete this series in java

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#24]
if you want to collaborate with other you can discuss there.

please note make a folder and name it "Hackerrank_30daysOFcode_in_Java"

note that I have already assigned this issue to some people in #2 so they are preferred first as they are already working on this issue

**Comment by Aastha26-lab** [comment]
hey , @rahulsain3000  Can I contribute to this issue . Please?

**Comment by muskanapp** [comment]
@rahulsain3000 Can you assign this to me?

**Comment by rahulsain3000** [comment]
ok @muskanapp as no one is assigned to JAVA  from #2 , I am assigning you.

Please try to complete this series(there is no time bound)

**Comment by Ayomal98** [comment]
Made the relevant java files from day 0 to day 5

**Comment by siddharthrajaraja** [comment]
@rahulsain3000  I have some in Java may I add them ?

**Comment by rahulsain3000** [comment]
hey @Ayomal98 @siddharthrajaraja maybe you can work together with @muskanapp for completing these series

**Comment by siddharthrajaraja** [comment]
@muskanapp  I have some solution may I ?

**Comment by siddharthrajaraja** [comment]
@rahulsain3000  @muskanapp  check #37

**Comment by muskanapp** [comment]
@siddharthrajaraja @Ayomal98 are you guys gonna add solutions for any other days as well? Otherwise, I am working on the solutions, I will add a few shortly.

**Comment by siddharthrajaraja** [comment]
@muskanapp  I have day 27 as well

**Comment by muskanapp** [comment]
@siddharthrajaraja Okay, then I will work on solutions from days 5-10.

**Comment by Ayomal98** [comment]
> @siddharthrajaraja @Ayomal98 are you guys gonna add solutions for any other days as well? Otherwise, I am working on the solutions, I will add a few shortly.

I have add from day 0 to day 5

**Comment by siddharthrajaraja** [comment]
@Ayomal98  fine by me 
@rahulsain3000  please mere #37  asap so that I may add more PRs

**Comment by rahulsain3000** [comment]
Ok @siddharthrajaraja

**Comment by siddharthrajaraja** [comment]
@rahulsain3000  I made a new PR #60

**Comment by rahulsain3000** [comment]
@Ayomal98 please add your code to the folder made by @siddharthrajaraja  and in your pr please delete your previous folder because it isn't opening

**Comment by Ayomal98** [comment]
> @Ayomal98 please add your code to the folder made by @siddharthrajaraja  and in your pr please delete your previous folder 'Hackerrank_30daysOFcode_in_Java' because it isn't opening

Sure I will

**Comment by gandalf0151** [comment]
@rahulsain3000 I want to collaborate with Java
I will be adding pr for days which aren't yet in 30 days of code Java
Please assign that issue to me

**Comment by rahulsain3000** [comment]
@gandalf0151 please discuss here with other developers

**Comment by gandalf0151** [comment]
Thanks @rahulsain3000 
@muskanapp I've solutions for Day 17 & beyond as of now
Is anyone else assigned for those

**Comment by muskanapp** [comment]
@gandalf0151 Nope, I am working on days 6-10.

**Comment by rahulsain3000** [comment]
> Thanks @rahulsain3000
> @muskanapp I've solutions for Day 17 & beyond as of now
> Is anyone else assigned for those
> Folder Hackerrank_30daysOFcode_in_Java isn't opening
> Should I add to another 30 days of Java

@gandalf0151 add to the other folder which is opening

**Comment by gandalf0151** [comment]
@muskanapp Then, should I do it for Day 11 till 20

**Comment by rahulsain3000** [comment]
Please note developer's should also update readme file and put a tick as shown in readme file for the files that are successfully merged with your PR request

**Comment by muskanapp** [comment]
@

> @muskanapp Then, should I do it for Day 11 till 20

okay

**Comment by muskanapp** [comment]
@siddharthrajaraja If you are adding solutions, let others know. Otherwise, there would be conflicts.

**Comment by siddharthrajaraja** [comment]
How to do that?

**Comment by siddharthrajaraja** [comment]
@everyone , I added a lot poblems in several languages please check the folder and make a PR accordingly . 
@rahulsain3000  can you please update the readme file?

**Comment by muskanapp** [comment]
A

> @everyone , I added a lot poblems in several languages please check the folder and make a PR accordingly .
> @rahulsain3000 can you please update the readme file?

Are you gonna add any more solutions? Or can I add some others?

**Comment by siddharthrajaraja** [comment]
@muskanapp  @everyone I added 23 and 24 in java

**Comment by siddharthrajaraja** [comment]
> A
> 
> > @everyone , I added a lot poblems in several languages please check the folder and make a PR accordingly .
> > @rahulsain3000 can you please update the readme file?
> 
> Are you gonna add any more solutions? Or can I add some others?

As I am completing adding them

**Comment by rahulsain3000** [comment]
> @everyone , I added a lot poblems in several languages please check the folder and make a PR accordingly .
> @rahulsain3000 can you please update the readme file?

sure i will update readme file soon

**Comment by siddharthrajaraja** [comment]
@rahulsain3000  merge the latest

**Comment by rahulsain3000** [comment]
@everyone only day 26 and day 29 left after that I close this issue

**Comment by gandalf0151** [comment]
@rahulsain3000 Day 20 added
Please take a look

**Comment by gandalf0151** [comment]
PR #103

**Comment by muskanapp** [comment]
@rahulsain3000 Day 29 added 
PR #104

**Comment by rahulsain3000** [comment]
Thank you everyone for participating.

Please check other issues if you're willing to contribute
