### ISSUE TITLE
complete this series in Python

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#25]
if you want to collaborate with other you can discuss there.

please note make a folder and name it "Hackerrank_30daysOFcode_in_Python"

note that I have already assigned this issue to some people in #2 so they are preferred first as they were already working on this issue

**Comment by h4rz** [comment]
@rahulsain3000, assign me.

**Comment by sherwin2000** [comment]
please give me this issue

**Comment by shalyavarnika** [comment]
assign me for python.

**Comment by kshitij9896** [comment]
Please Assign me for python

**Comment by rahulsain3000** [comment]
please check that till day7 has been merged

**Comment by rahulsain3000** [comment]
@sherwin2000 @kshitij9896 @shalyavarnika  please collaborate with @h4rz as he is already assigned

**Comment by h4rz** [comment]
@sherwin2000, @kshitij9896, @shalyavarnika, if you guys are ahead of day7 then you could contribute else it would just cause conflicts or duplicate/multiple solutions of the same problem. Please discuss in the comments on which solution you guys will be working so that no other dev uploads the same solution.

**Comment by rahulkranjan** [comment]
Can I work in python on this?

**Comment by rahulsain3000** [comment]
@rahulkranjan Please check readme file and start working on these code with other here

**Comment by ViAsmit** [comment]
I will be working for Day 27 .

**Comment by priya1011** [comment]
I will be working on day 14 in python. Assign the issue to me too.

**Comment by rahulsain3000** [comment]
Note @everyone that only day 17 and day 21 code are left to be merged. After that I will close this issue

**Comment by h4rz** [comment]
@rahulsain3000, I will work on day21

**Comment by rahulsain3000** [comment]
Ok @h4rz

**Comment by h4rz** [comment]
@rahulsain3000, I just checked that day21 is invalid for python as python is a dynamic language. In python, we use `list` as an array and the `list` can take items of any data-type/object. Even Hackerrank only allows the solution to be in C++, java, and swift. 

We can do 2 things, either mark the question as invalid for python or else I could create a method `printArray(list)` which takes a list as a parameter and the job will be to loop and print the items.

**Comment by rahulsain3000** [comment]
Ok @h4rz mark Day 21.py and Day27.c as invalid
