### ISSUE TITLE
complete this series in any other langauge that is not mentioned in issue section

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#26]
if you want to collaborate with other you can discuss there.

please note make a folder and name it "Hackerrank_30daysOFcode_in_your_language"

note that I have already assigned this issue to some people in #2 so they are preferred first as they are already working on this issue

**Comment by Harshit564** [comment]
I want to collaborate. Please assign the issue @rahulsain3000

**Comment by rahulsain3000** [comment]
@Harshit564 in which language are you willing to complete this series?

**Comment by Harshit564** [comment]
> @Harshit564 in which language are you willing to complete this series? 

C#

**Comment by rahulsain3000** [comment]
OK @Harshal0506 assigned.

**Comment by zackmolt** [comment]
I want to collaborate

**Comment by Bharathwaj3003** [comment]
@rahulsain3000  I see that all are working in python, C# and C++. Can I work in C and other languages I want?

**Comment by rahulsain3000** [comment]
@zackmolt sure i can assign you for Kotlin please make a separate folder for that

**Comment by GauravPoosarla** [comment]
Can i Work on C or Python any of the two is fine for me?

**Comment by rahulsain3000** [comment]
@GauravPoosarla Please discuss with other assignees for that particular language

**Comment by Bharathwaj3003** [comment]
@rahulsain3000 I am already working in C. can i work with BASH and rust too?

**Comment by Bharathwaj3003** [comment]
@rahulsain3000 Can you create a issue for BASH and rust for me?

**Comment by rahulsain3000** [comment]
@Bharathwaj3003 make your contribution side by side in other language(BASH and rust) in your local repo and send the PR when once your contribution on C language is completed

**Comment by Bharathwaj3003** [comment]
@rahulsain3000 is it necessary that i should write in .md files. Because i really dont know how to write in .md

**Comment by rahulsain3000** [comment]
@Bharathwaj3003  can write in .c and @Harshal0506 can convert it in .md if not a problem

**Comment by Harshal0506** [comment]
yes i will change it to md file  i have no issue @Bharathwaj3003  can we connect on linkedin ?
[ linkedin profile ]( https://www.linkedin.com/in/harshal-rajesh-jain/ )

**Comment by AmosAidoo** [comment]
So in case I want to contribute in a new language, I'll just have to make a pull request?

**Comment by rahulsain3000** [comment]
Yes @AmosAidoo

**Comment by AmosAidoo** [comment]
Great. Thank you @rahulsain3000

**Comment by vasavraj** [comment]
I want to contribute in whatever language you need @rahulsain3000

**Comment by rahulsain3000** [comment]
@vasavraj complete JavaScript

**Comment by vasavraj** [comment]
@rahulsain3000 I will try to contribute asap.

**Comment by AMorr1** [comment]
@rahulsain3000 i will try to contribute asap in C++

**Comment by AmosAidoo** [comment]
@AMorr1 @Suhani028 I think if someone is already working on a language, you will have to arrange with the person so that you can help.

**Comment by anurag-bhatt** [comment]
@rahulsain3000  i can contribute in Java

**Comment by esheetaparulekar** [comment]
Can I try to contribute in Java @rahulsain3000 ?

**Comment by rahulsain3000** [comment]
@AMorr1 Hey buddy, note that solutions for Java and C++ are up to date. Please try to collaborate with other developers for other language.

**Comment by 0tist** [comment]
Hey @rahulsain3000, I would like to complete the series in Swift

**Comment by karansharma007** [comment]
hey @rahulsain3000 , I would like to complete it in typescript

**Comment by rahulsain3000** [comment]
@0tist @karansharma007 Sure, but try to complete the series in just 4 5 PR and make required changes in readme file

**Comment by 0tist** [comment]
sure thing, a quick question, would you require to convert the python scripts to notebook by any chance?

**Comment by rahulsain3000** [comment]
@0tist Is notebook another language, can you explain in more detail about notebook and how will it help this repo.

**Comment by 0tist** [comment]
Thanks for your prompt response, to be precise, I was talking about converting python scripts to python notebooks, if not i can look into julia, that would require some time, also, do i have to create a new issue in order for you to assign me for Swift?

**Comment by rahulsain3000** [comment]
@0tist No need to create an issue if you are eagerly want to complete in your chosen language. If at any moment I think that you stop your work in the middle then I will create an issue and asking other contributors to work on it. 

Do in any desired language but it must be complete. As only some people know these language so it will be difficult for other contributors to work on an unknown language.

**Comment by 0tist** [comment]
sure 👍🏼

**Comment by varshaig1999** [comment]
@rahulsain3000 can I work on c++? Since I saw no comments on c++. I will really like to make my contribution to this.
@AMorr1 is there any bug I can fix and help regarding c++?

**Comment by rahulsain3000** [comment]
Sorry C++ language is complete

**Comment by arnav1598** [comment]
Hey, can I contribute with Python? I think one of the problem still requires a solution in python.

**Comment by pkpawankushwaha** [comment]
@rahulsain3000 I started doing it in PHP and added it for 6days

**Comment by 7vikpeculiar** [comment]
@rahulsain3000  Can I work on doing it in Julia? I have previous experience with it ?

**Comment by pawan-git7979** [comment]
Hey bro, i  am  really excited in your repo as i have myself also completed the 30 days code challange on **hackerank** 6-7 months ago. but my preference language that i code in is "**C++**" followed by "**C**".
I m seeing that all the ques of the 30 day series already have been answered on the repo in c++, so,  please u can assign me some task that in C++ language.

**Comment by rahulsain3000** [comment]
@pawan-git7979 Hey , you can modify/update the existing code and check if the code is passing all the test cases or not.
Any comment added to existing code for readability is welcome here. Looking forward to your contribution.

**Comment by rahulsain3000** [comment]
@7vikpeculiar Sure, make sure you add a column for julia in readme file.

**Comment by aditya9110** [comment]
@rahulsain3000 can I contribute for python?

**Comment by rahulsain3000** [comment]
@aditya9110 Code for Python is already complete. You can enchance/update the code if it has some errors though

**Comment by Abhishek4uh** [comment]
@rahulsain3000 Hey Can I work on this repo? Pls assign this to me

**Comment by rahulsain3000** [comment]
@Abhishek4uh What are your suggestions that you will contribute?

**Comment by amitShindeGit** [comment]
Hey rahulsain3000,can i do this in Java, if not done already.

**Comment by EktaAgrawal1567** [comment]
Hi, can I contribute in C language ?

**Comment by rahulsain3000** [comment]
@amitShindeGit Java, C++,Python, C and JS are already completed

**Comment by sunny52525** [comment]
I can do it in Kotlin.

**Comment by rahulsain3000** [comment]
Sure @sunny52525 just complete your work in no more than 4 5 PR and please update readme file also

**Comment by sunny52525** [comment]
> Sure @sunny52525 just complete your work in no more than 4 5 PR and please update readme file also

Just saw now that there are some questions which don't have kotlin as an option, so am I supposed to leave them and move to next one, right?

**Comment by rahulsain3000** [comment]
Yes @sunny52525 and mark them as cross in readme file too

**Comment by saaranshM** [comment]
Can I contribute in python?

**Comment by rahulsain3000** [comment]
@saaranshM , @karansharma007  is already working on that you can collaborate with him regarding this.

**Comment by saaranshM** [comment]
@karansharma007 Can I work on day5 of typescript?

**Comment by karansharma007** [comment]
@saaranshM , sure. You can work on day6 too if you like.

**Comment by SudiptaAChy** [comment]
Hi can i contribute with Dart language?

**Comment by saaranshM** [comment]
@karansharma007 thanks!

**Comment by megatron100** [comment]
hey @rahulsain3000 Can i contribute in GO?

**Comment by rahulsain3000** [comment]
@SudiptaAChy Sure.
@megatron100 Yes please

**Comment by ravish0007** [comment]
can I do it in python ?

**Comment by Harshal0506** [comment]
hey @rahulsain3000 sorry its a offtrack question one of my friend want people to enhance his website css ,html how can he put his repositiory in hacktober fest ? Can one apply for it ?

As it will help my friend as well as the contributor trying to open source 
Thanks for being there to answer as always

**Comment by rahulsain3000** [comment]
Join the discord server and ping me there @Harshal0506

**Comment by SincerelyBrittany** [comment]
May I contribute in Ruby?

**Comment by rahulsain3000** [comment]
Sure @SincerelyBrittany
