### ISSUE TITLE
C/C++ Solution Updations

### ISSUE THREAD

**Issue by Kailash108** [rahulsain3000/Hackerrank_30daysOFcode#263]
Hello,
I am planning to update some C/C++ codes.
Pls accept.
Thanks.

**Comment by rahulsain3000** [comment]
Sure any contribution is valuable here.

**Comment by saiharsha-22** [comment]
@rahulsain3000 I have added day 18 solutions for c program and sent pull request #321 can you please check it once.

**Comment by Amulya-coder** [comment]
@rahulsain3000 the day 20 solution doesn't seems to look correct and very efficient. Can I update it . Please assign it to me. Thanks.

**Comment by rahulsain3000** [comment]
@Amulya-coder Sure

**Comment by Amulya-coder** [comment]
@rahulsain3000 Changes have been made have a look.
