### ISSUE TITLE
Updating the Python codes to reduce the time complexity 

### ISSUE THREAD

**Issue by nikkkhil067** [rahulsain3000/Hackerrank_30daysOFcode#264]
Hi I am planning to update the Python and C++ Codes.
I can work on reducing the time complexity of all the 30 problems.
So, please assign this to me.

**Comment by rahulsain3000** [comment]
Hey, @nikkkhil067 someone is already assigned for C++, but you can contribute in Python.
Looking forward for your valuable contribution.

**Comment by nikkkhil067** [comment]
Thanks I will start contributing now.

**Comment by rahulsain3000** [comment]
@nikkkhil067 Are you still working on it?

**Comment by nikkkhil067** [comment]
Yes, will be finished updating today

**Comment by rahulsain3000** [comment]
> Yes, will be finished updating today

@nikkkhil067 when you're done close this issue too

**Comment by nikkkhil067** [comment]
Done Updating!
