### ISSUE TITLE
Completing the left questions in Python

### ISSUE THREAD

**Issue by yash982000** [rahulsain3000/Hackerrank_30daysOFcode#270]
I am solving all those which are left for python

**Comment by yash982000** [comment]
I have solved the Generics in Python. Let me know if I can create the pull request.

**Comment by VenkatVuddagiri** [comment]
Which day questions are left?

**Comment by rahulsain3000** [comment]
There are so question left, they cant be implemented using Python that what the contributors told me.

**Comment by yash982000** [comment]
They can be. Generics is left.

**Comment by yash982000** [comment]
Technically, it is not available for the hackerrank submission but those who want to think out of the box can typically try it in python and I have that part. It would be very helpful for people knowing only Python

**Comment by VenkatVuddagiri** [comment]
I've made a pr for generics in java already. It got merged. Closes #270

**Comment by yash982000** [comment]
Yes but, I am telling for Python. There is still a cross over there.

**Comment by rahulsain3000** [comment]
@yash982000 ok waiting for your contribution.
Thanks for the clarification.

**Comment by yash982000** [comment]
@rahulsain3000 Can I open a PR for a solution in Python?
I guess to do it in all languages is our task and so it shouldn't be a problem.

**Comment by yash982000** [comment]
Ohh, okay thanks doing. @rahulsain3000

**Comment by yash982000** [comment]
Done @rahulsain3000

**Comment by yash982000** [comment]
Thanks, @rahulsain3000  Let me know if some other such remaining stuff is left. Also, can you label those issues with Hactoberfest?

**Comment by rahulsain3000** [comment]
@yash982000  if you're willing to contribute then you can make update in readme file on regular basis at mid night or so by checking recently merged files that wasn't updated by the contributors when they add/create (not update) code

**Comment by yash982000** [comment]
@rahulsain3000 Okay, sure, I will do that at night and accumulate all from the recent PR changes.

**Comment by rahulsain3000** [comment]
Ok @yash982000 thanks for lending a helping hand #283 please comment here so I can assign you
