### ISSUE TITLE
Add tick mark in README.md file 

### ISSUE THREAD

**Issue by VenkatVuddagiri** [rahulsain3000/Hackerrank_30daysOFcode#283]
Please mark tick and cross to respective problem, make sure to read readme file before making a PR.
Opened this issue to help beginners in the fest.

**Comment by rahulsain3000** [comment]
Ok

**Comment by VenkatVuddagiri** [comment]
I would do that @rahulsain3000 . But I thought it would help others.

**Comment by yash982000** [comment]
I will do this

**Comment by rahulsain3000** [comment]
@VenkatVuddagiri I understand that you want to help beginner's contribute to this project. That's why I have edited some things.
@yash982000 welcome to the community.

**Comment by VenkatVuddagiri** [comment]
@rahulsain3000  Okay

**Comment by yash982000** [comment]
@rahulsain3000 Thank you very much. I hope I can be helpful. Let us all connect:- https://www.linkedin.com/in/yash-patel-970517166/

**Comment by rahulsain3000** [comment]
Maybe we should create a mass gathering spot like discord for this community.

**Comment by yash982000** [comment]
I also strongly believe. I am a hardcore community guy and part of more than 20+ communities.

**Comment by rahulsain3000** [comment]
Great @anybody know how to create discord server here?

**Comment by VenkatVuddagiri** [comment]
Yes @rahulsain3000 I know how to create a discord server and currently I'm managing one. I can help you create one.

**Comment by hnishal** [comment]
> Great @AnyBody know how to create discord server here?
its, no big deal
lemme know if you need help

**Comment by rahulsain3000** [comment]
@VenkatVuddagiri @hnishal Can you create a server for this community.

**Comment by VenkatVuddagiri** [comment]
> @VenkatVuddagiri @hnishal Can you create a server for this community.

Yes bro

**Comment by rahulsain3000** [comment]
Ok add me Rahuldchamp#3336 at discord will discuss further there.

**Comment by hnishal** [comment]
> > @VenkatVuddagiri @hnishal Can you create a server for this community.
> 
> Yes bro

If you making it add me there @Nishal#9167

**Comment by rahulsain3000** [comment]
> > > @VenkatVuddagiri @hnishal Can you create a server for this community.
> > 
> > 
> > Yes bro
> 
> If you making it add me there @nishal#9167

Link is https://discord.gg/XS9NvNt
Will be adding this in readme file soon

**Comment by rahulsain3000** [comment]
@yash982000 Why didn't you make a PR for which you were assigned to? It make a havoc between the contributors and there is conflict over the same file across different PR

**Comment by yash982000** [comment]
@rahulsain3000  I am doing right now, also merge my latest pull changes. We need to define in the repo, how to contribute to one issue at a time. We will take whomsoever has done first.

**Comment by rahulsain3000** [comment]
@yash982000 Please join discord server #318
