### ISSUE TITLE
SOLVING PROBLEMS IN JAVA

### ISSUE THREAD

**Issue by mishraaditya20142014** [rahulsain3000/Hackerrank_30daysOFcode#298]
hello Sir, I am planning to solve the problems using JAVA.

**Comment by mishraaditya20142014** [comment]
Could You Please Assign Me Some Of the problems to help me create 4 or more valid PRs.

**Comment by nuclearcheesecake** [comment]
I would also like working on the Java problems! :)

**Comment by megatron100** [comment]
> hello Sir, I am planning to solve the problems using JAVA.

hey @mishraaditya20142014  can you help me how to contribute in above issue and make a valid pull request to eligible for hacktoberfest2020. I am new to git so?

**Comment by rahulsain3000** [comment]
The code for JAVA,C++,Python , and some more are complete however you guys could enhance/update the code which leads to better understandability of the code and it will help you in your 4 valid PR for this fest.

**Comment by rahulsain3000** [comment]
Or you can make a solution set 2 folder like #313 did in PR, but the solution must be different with pre existing set of solutions

**Comment by mishraaditya20142014** [comment]
Okay Sir, Keeping Your Points In mind. I'll Start it today.. Hope it goes Fine... Thank you..

**Comment by rahulsain3000** [comment]
@mishraaditya20142014 You are still working on it right?

**Comment by mishraaditya20142014** [comment]
yes, I am... Will submit rest of The programs soon...

**Comment by rahulsain3000** [comment]
Ok @mishraaditya20142014

**Comment by rahulsain3000** [comment]
@mishraaditya20142014 Close the issue when you're done

**Comment by mishraaditya20142014** [comment]
Sorry Sir, due to electricity shortage none of my devices were charged yesterday. That's why I was unable to follow up..

**Comment by rahulsain3000** [comment]
@mishraaditya20142014 Ok, so you're still doing this issue?

**Comment by mishraaditya20142014** [comment]
Yes Sir, I am trying a few more problems. 5-6 more problems...

**Comment by rahulsain3000** [comment]
Ok

**Comment by mishraaditya20142014** [comment]
Thank you Sir...

**Comment by mishraaditya20142014** [comment]
A problem is always showing this error... Can't automatically merge...  Thus, unable to create PR for this day26 problem...

**Comment by mishraaditya20142014** [comment]
Trying to do it, 5 commits have been done by mistake. Sorry about that, Sir.

**Comment by mishraaditya20142014** [comment]
Getting the same errors for next problem also, Sir...

**Comment by rahulsain3000** [comment]
@mishraaditya20142014 Delete the repo on your side and re-fork it from here
