### ISSUE TITLE
Change files' naming convention

### ISSUE THREAD

**Issue by AhmedElsisy** [rahulsain3000/Hackerrank_30daysOFcode#315]
Change files' naming convention to make it sorted correctly for **GitHub** GUI users, as you can see in the picture below the files are not sorted by the number of the day (`day2.cpp` comes after `day19.cpp`, etc.) but lexicographically.

![image](https://user-images.githubusercontent.com/28100837/95004879-5b2f0f00-05f1-11eb-9dc9-5ce533cb5d89.png)

for many **GitHub** GUI users, it can mislead them in searching for a specific file.

**suggested solution:** add a leading zero to all single-digit files,
for example, _"`day2.extension`"_ is changed to _"`day02.extension`"_.

you can add this naming convention to the contribution style convention.

**Comment by NayakNavin** [comment]
Hi can i work on this ?

**Comment by rahulsain3000** [comment]
@AhmedElsisy is already assigned sorry

**Comment by rahulsain3000** [comment]
Please change file name convention to this format -> `day01.extension` and not `day1.extension` manually

**Comment by NayakNavin** [comment]
> @AhmedElsisy is already assigned sorry please try other issues mentioned

ok

**Comment by rahulsain3000** [comment]
@NayakNavin Join discord at #318 I have some work you can work on too
