### ISSUE TITLE
I want to add a resource folder for programming books

### ISSUE THREAD

**Issue by amishaagarwal1998** [rahulsain3000/Hackerrank_30daysOFcode#334]

**Comment by amishaagarwal1998** [comment]
Please assign to me if we are going ahead with this.

**Comment by rahulsain3000** [comment]
1. Is these recourses free on the internet?
2. How will these books will help on the repo?
3. You could paste those link on the discord server itself so it might not be a hinderance to this repo.
@amishaagarwal1998

**Comment by amishaagarwal1998** [comment]
Yes, they are mostly available on internet but as per me people are mostly unaware of **which** books to refer to. Hence we can add such quality books!

**Comment by rahulsain3000** [comment]
@amishaagarwal1998 check discord I have mentioned you

**Comment by hnishal** [comment]
@rahulsain3000 make sure these contents are not a subject to copyright. We can set up a different repo for this

**Comment by rahulsain3000** [comment]
@hnishal Right, that's why I have asked @amishaagarwal1998 to put these in discord or else a different repo would be better

**Comment by rahulsain3000** [comment]
I am closing this issue as on 'No reply within 24 hours'
