### ISSUE TITLE
Improve readability in README

### ISSUE THREAD

**Issue by h4rz** [rahulsain3000/Hackerrank_30daysOFcode#34]
I'm thinking to add a tabular format in readme.md where each problem name will be present with their link to Hackerrank's website, their status whether it is implemented or not in a particular language. 

Eg.
| Day   	| Problem Statement  	| Python   	| C  	| C++  	| Java  	| Javascript  	|
|---	|---	|---	|---	|---	|---	|---	|
|  00 	|  [Hello, World.](https://www.hackerrank.com/challenges/30-hello-world/problem)  	| :white_check_mark:  	|   	|   	|   	|   	|

Assign it to me, if you find this valid.

**Comment by rahulsain3000** [comment]
Yeah, but how should we update this readme file regularly after each PR  merged?

**Comment by h4rz** [comment]
I would add all the program name, each developer before raising a PR, has to put a :white_check_mark: in the language column of the program, he/she has implemented.

**Comment by rahulsain3000** [comment]
Okay nice idea

**Comment by hnishal** [comment]
@rahulsain3000 @h4rz can anyone of you create an image directory and add some screenshots or some reference images(related to 30days of code/hacckerank) in it.

**Comment by hnishal** [comment]
@rahulsain3000 after merging this pull request assign me this issue, i'll a few things

**Comment by rahulsain3000** [comment]
please update readme file with recent merges @hnishal

**Comment by hnishal** [comment]
@rahulsain3000 any feedback?

**Comment by rahulsain3000** [comment]
@hnishal great work! It is easy to read for beginner coming at Github. 

Please add a line asking developers to mark as completed in readme file.

**Comment by sdoss93212** [comment]
Anything I can to the readme??

**Comment by rahulsain3000** [comment]
@sdoss93212 You could mark (✅ ) to the files that are successfully merge till now.

**Comment by sdoss93212** [comment]
> @sdoss93212 You could mark (✅ ) to the files that are successfully merge till now.

Ok I'm on it!

**Comment by rahulsain3000** [comment]
i am updated readme file as per latest merge to avoid conflict. Thanks @h4rz for contributing and suggesting me this idea.

**Comment by rahulsain3000** [comment]
This issue is shifted here #117
