### ISSUE TITLE
Create links to the files with :white_check_marks:

### ISSUE THREAD

**Issue by 0tist** [rahulsain3000/Hackerrank_30daysOFcode#341]
I wish to propose an enhancement for the README.md file, we can have links attached to the ✅ , such that it leads to the desired solution in the preferred language
### Example: Click on the tick mark for Day 5's solution in swift [✅ ](https://github.com/rahulsain3000/Hackerrank_30daysOFcode/blob/master/30daysOFcode_Swift/Day5.swift)

**Comment by rahulsain3000** [comment]
Hey @0tist I like your idea, join discord #318 we will talk about this there

**Comment by 0tist** [comment]
a simple way to add link to the checkmark:  `[✅ ](https://github.com/rahulsain3000/Hackerrank_30daysOFcode/blob/master/30daysOFcode_Swift/day%2005.swift)`

**Comment by rahulsain3000** [comment]
Great @0tist

**Comment by rahulsain3000** [comment]
@0tist Please stop your work temporarily because I am still receiving PR that may cause conflict on readme file

**Comment by 0tist** [comment]
Tbh, I wasnt working on this, was expecting some response from other contributors

**Comment by rahulsain3000** [comment]
Ok @0tist thanks for the info.

**Comment by hnishal** [comment]
implementing this would be really hectic

**Comment by rahulsain3000** [comment]
> implementing this would be really hectic

Well its not necessary, I am thinking to assign this issue at last when the repo is complete

**Comment by VenkatVuddagiri** [comment]
Idea is really good one
But 1 person implementing all these would be really difficult
So split the issue into different languages

**Comment by rahulsain3000** [comment]
@VenkatVuddagiri Yes, I will assign 1 person for 1 language

**Comment by 0tist** [comment]
@rahulsain3000 you don't really have to assign anyone, I want newbie contributors to think of it as removing typos or something similar, this way they will explore the repo and will get to practice git

**Comment by rahulsain3000** [comment]
@0tist So, you mean that I need not to assign this to anyone, everyone can contribute to this issue.
In this way, they will open the every code of the repo and hence it will help them practicing git and github and md file too?
