### ISSUE TITLE
Error showing 0!(factorial) it stucks up in a recursive loop

### ISSUE THREAD

**Issue by Siddhant-sarkar** [rahulsain3000/Hackerrank_30daysOFcode#359]
In the 30Days_Of_Code_Java in day9.java contains a recursive code in which the factorial is to found out but when finding zero factorial it ends up in being in an endless loop.

**Comment by rahulsain3000** [comment]
@Siddhant-sarkar Thanks for the info, successfully merged your PR and appreciate your valuable contribution.
