### ISSUE TITLE
add cross to readme file

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#361]
Please add ❌ to all the problem which cant be done on that particular language at Hackerrank.

>Note:  Only apply cross to the problem which dont have ✅ in it. In other words, to **incomplete problem**

**Comment by amitoj-singh** [comment]
Hello, Can I work on this issue?

**Comment by rahulsain3000** [comment]
Sure @amitoj-singh
