### ISSUE TITLE
Add explanation comments on day 03 js

### ISSUE THREAD

**Issue by leonyangela** [rahulsain3000/Hackerrank_30daysOFcode#375]
Hello, I would like to add an explanation comment on the Javascript sections day03. Is it okay? Thank you
![image](https://user-images.githubusercontent.com/38250310/95064698-51f58d80-072a-11eb-8c81-8aa4c2ba1d22.png)

**Comment by rahulsain3000** [comment]
Sure @leonyangela

**Comment by leonyangela** [comment]
Thank you
