### ISSUE TITLE
Add explanation comments to day 09 on 30daysOFcode_Javascript

### ISSUE THREAD

**Issue by leonyangela** [rahulsain3000/Hackerrank_30daysOFcode#380]
Hello, I would like to add an explanation comments to day 09 on 30daysOFcode_Javascript. Thank you.
![image](https://user-images.githubusercontent.com/38250310/95070597-8e2cec00-0732-11eb-9573-b7e8e2893544.png)

**Comment by rahulsain3000** [comment]
Go ahead @leonyangela
