### ISSUE TITLE
Complete the codes which are left 

### ISSUE THREAD

**Issue by rahulsain3000** [rahulsain3000/Hackerrank_30daysOFcode#392]
Complete the codes which are left blank on readme file on any **language**

> make sure to ✅ those problem on readme file too

**Comment by Jade9ja** [comment]
I would like to work on the binary search trees (22) problem in typescript, please assign it to me. (Or should I open a new issue? )

**Comment by jordanhilado** [comment]
Hello! I am willing to work on this for Hacktoberfest. :) How many would you like me to complete for this issue to be resolved?

**Comment by JayavardhaniKathika** [comment]
Hello, can I work on this issue for Hacktoberfest?

**Comment by luminousbeam** [comment]
Hello, I'd like to work on the Generics problem using Javascript and also in Typescript. I don't see a folder for these problems here, where can I find them or would I need to create my own folder?

**Comment by luminousbeam** [comment]
> Hello, I'd like to work on the Generics problem using Javascript and also in Typescript. I don't see a folder for these problems here, where can I find them or would I need to create my own folder?

Ah, I just realized that this problem is labeled as Day 21! Let me know if I can contribute to that problem in both languages, thanks.

**Comment by rahulsain3000** [comment]
> > Hello, I'd like to work on the Generics problem using Javascript and also in Typescript. I don't see a folder for these problems here, where can I find them or would I need to create my own folder?
> 
> Ah, I just realized that this problem is labeled as Day 21! Let me know if I can contribute to that problem in both languages, thanks.

@luminousbeam I think day21 problem cant be done in those specified language if you could solve it some how, I would be glad. Just make sure to update readme file too

**Comment by rahulsain3000** [comment]
> Hello! I am willing to work on this for Hacktoberfest. :) How many would you like me to complete for this issue to be resolved?

@jordanhilado Sure, you can check that how could you help in this repo and a new issue of it. It can be anything adding/updation of code or enhancing readme/contributing file or any new idea that would help the sole purpose of this repo

**Comment by kambleaa007** [comment]
I like to take TypeScript, assign me one

**Comment by rahulsain3000** [comment]
@kambleaa007 Make a new issue describe what will you do and I will assign you there
