### ISSUE TITLE
Complete C# problems

### ISSUE THREAD

**Issue by andyalmeida** [rahulsain3000/Hackerrank_30daysOFcode#396]
Hello, it's missing three C# problems. From these two can be solved. I'd like to complete them. 

And a suggestion to the problems that can't be solved. Why don't use a different symbol like ✖️, ⛔ or 🚫, so we can differ the problems that are missing from the ones that can't be solved.

**Comment by rahulsain3000** [comment]
@andyalmeida Sure, go ahead. We are using ❌ for the problem that can't be solved but it seems that there is some error or maybe they cant be really solved on Hackerrank website
