### ISSUE TITLE
Day 21: Generics for JavaScript

### ISSUE THREAD

**Issue by kambleaa007** [rahulsain3000/Hackerrank_30daysOFcode#417]
In TypeScript, we can generics for interfaces as well as classes,
Assign me Day 21: Generics for language TypeScript and JavaScript,
They are possible

**Comment by rahulsain3000** [comment]
Go ahead

**Comment by kambleaa007** [comment]
JavaScript is a dynamically typed language and it doesn't have any generics. You can write a normal function/method, it will work for all types.

Still I tried it using ES6 with class and extends keywords, i followed stackoverflow answers

**Comment by rahulsain3000** [comment]
Ok @kambleaa007 is it working?

**Comment by kambleaa007** [comment]
yepp,
I have tested for Array, String
![image](https://user-images.githubusercontent.com/19818679/95293794-c1d25800-0891-11eb-99a4-a93710c73a6b.png)
